name: Github Telegram Notifier
uses: EverythingSuckz/github-telegram-notify@main
on:
  push:
    branches: [main]
with:
  bot_token: '${{ secrets.TELEGRAM_NOTIFIER_TOKEN }}'
  chat_id: '${{ secrets.CHAT_ID }}'
          
